import type { Metadata } from "next";
import "./globals.css";
import MainHeaderBackground from "@/components/main-header-background";
import MainHeader from "@/components/main-header";
import MainFooter from "@/components/main-footer";
import ReduxProvider from "@/redux/redux-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <MainHeaderBackground />
          <MainHeader />
          {children}
          <MainFooter />
        </ReduxProvider>
      </body>
    </html>
  );
}
